name: Build Firmware
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # 消除 Node 20 警告
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
      - name: Build My Keyboard
        # 增加 --extra-experimental-features 确保 nix 命令兼容
        run: nix build .#keyboards.my6key --extra-experimental-features "nix-command flakes"
      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: ch552-firmware
          path: result/
